"""privacy_audit 模块测试：pubspec.lock 解析 + 追踪-SDK 排除名单命中检测。

契约（与 docs/privacy-android.md 口径一致）：
- 「零第三方 SDK 追踪」= 依赖树（pubspec.lock 直接 + 传递全量包名）命中排除名单条数为 0；
- 排除名单按「包名字串子串」匹配——负样本（含 appsflyer / sentry 等模拟条目）必须能被命中；
- 既有功能库（drift / dio / flutter_secure_storage / webview_flutter / share_plus /
  path_provider 等）不得命中名单；
- 空依赖样本通过（无漏报误报）。
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# 仓库根入 path，使 `scripts.privacy_audit` 可解析（与覆盖率门 `--cov=scripts/privacy_audit.py`
# 的文件路径对齐；裸 `from privacy_audit import ...` 亦可经 scripts 目录在 PYTHONPATH 复用）
REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import scripts.privacy_audit as privacy_audit  # noqa: E402
from scripts.privacy_audit import (  # noqa: E402
    TRACKING_PATTERNS,
    audit_lockfile,
    audit_project,
    main,
    parse_lock_packages,
    parse_pubspec_direct_names,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
LOCK = REPO_ROOT / "pubspec.lock"


def _lock_text(packages: dict[str, str]) -> str:
    """构造最小合法 pubspec.lock 文本：包名 -> dependency 类型（transitive / direct main）。"""
    lines = ["# Generated by pub", "packages:"]
    for name, kind in packages.items():
        lines.append(f"  {name}:")
        lines.append(f"    dependency: {kind}")
        lines.append("    description:")
        lines.append(f"      name: {name}")
        lines.append('      url: "https://pub.dev"')
        lines.append("    source: hosted")
        lines.append('    version: "1.0.0"')
    lines.append("sdks:")
    lines.append('  dart: ">=3.13.2 <4.0.0"')
    return "\n".join(lines)


def _write_project(tmp_path: Path, pubspec: str, lock: str) -> None:
    (tmp_path / "pubspec.yaml").write_text(pubspec, encoding="utf-8")
    (tmp_path / "pubspec.lock").write_text(lock, encoding="utf-8")


class TestParseLock:
    def test_parse_real_lock_full_count_and_kinds(self):
        pkgs = parse_lock_packages(LOCK.read_text(encoding="utf-8"))
        assert len(pkgs) >= 100
        by = {p.name: p for p in pkgs}
        assert by["dio"].dependency_kind == "direct main"
        assert by["analyzer"].dependency_kind == "transitive"
        assert by["flutter"].source == "sdk"
        assert by["flutter"].dependency_kind == "direct main"
        assert by["flutter_secure_storage"].version == "11.0.0"
        assert "sdks" not in by  # sdks 段不得混入包名单

    def test_empty_lock_returns_no_packages(self):
        assert parse_lock_packages("") == []
        assert parse_lock_packages("packages:\n") == []
        assert parse_lock_packages("sdks:\n  dart: \"x\"\n") == []

    def test_unquoted_version_and_sdk_description(self):
        text = "\n".join(
            [
                "packages:",
                "  foo:",
                "    dependency: direct main",
                "    description: flutter",
                "    source: sdk",
                "    version: 0.0.0",
            ]
        )
        pkgs = parse_lock_packages(text)
        assert len(pkgs) == 1
        assert pkgs[0].name == "foo"
        assert pkgs[0].version == "0.0.0"
        assert pkgs[0].source == "sdk"

    def test_stray_indented_line_does_not_break(self):
        text = "\n".join(
            [
                "packages:",
                "  foo:",
                "    dependency: transitive",
                "    description:",
                "      name: foo",
                "    source: hosted",
                '    version: "1.0.0"',
                "  ~broken-line",
                "  bar:",
                "    dependency: transitive",
                "    source: hosted",
                '    version: "2.0.0"',
            ]
        )
        pkgs = parse_lock_packages(text)
        assert [p.name for p in pkgs] == ["foo", "bar"]

    def test_blank_line_inside_packages_section(self):
        text = "\n".join(
            [
                "packages:",
                "",
                "  foo:",
                "    dependency: transitive",
                "    source: hosted",
                '    version: "1.0.0"',
                "",
                "  bar:",
                "    dependency: transitive",
                "    source: hosted",
                '    version: "2.0.0"',
            ]
        )
        pkgs = parse_lock_packages(text)
        assert [p.name for p in pkgs] == ["foo", "bar"]

    def test_invalid_indented_line_before_first_entry_is_skipped(self):
        text = "\n".join(
            [
                "packages:",
                "  ???",
                "  foo:",
                "    dependency: transitive",
                "    source: hosted",
                '    version: "1.0.0"',
            ]
        )
        pkgs = parse_lock_packages(text)
        assert [p.name for p in pkgs] == ["foo"]


class TestPubspecDirectNames:
    def test_extracts_direct_names_with_nested_and_comments(self):
        text = "\n".join(
            [
                "name: demo",
                "# 注释行不应中断依赖节",
                "dependencies:",
                "  dio: ^5.11.0",
                "  drift:",
                "    path: ../drift",
                "  flutter:",
                "    sdk: flutter",
                "dev_dependencies:",
                "  flutter_lints: ^6.0.0",
                "flutter:",
                "  uses-material-design: true",
            ]
        )
        assert parse_pubspec_direct_names(text) == [
            "dio",
            "drift",
            "flutter",
            "flutter_lints",
        ]


class TestTrackingDetection:
    FAKE_TRACKING = {
        "firebase_core": "transitive",
        "appsflyer_sdk": "transitive",
        "sentry_flutter": "direct main",
        "amplitude_flutter": "transitive",
        "mixpanel_flutter": "transitive",
        "adjust_sdk": "transitive",
        "braze_plugin": "transitive",
        "flutter_branch_sdk": "transitive",
        "clevertap_flutter": "transitive",
        "kochava_flutter": "transitive",
        "firebase_crashlytics": "transitive",
    }

    def test_negative_sample_all_hit(self):
        result = audit_lockfile(_lock_text(self.FAKE_TRACKING))
        assert result.package_count == len(self.FAKE_TRACKING)
        assert set(result.hits) == set(self.FAKE_TRACKING)
        assert not result.is_clean

    def test_functional_libraries_not_hit(self):
        functional = {
            "drift": "direct main",
            "dio": "direct main",
            "flutter_secure_storage": "direct main",
            "webview_flutter": "direct main",
            "share_plus": "direct main",
            "path_provider": "direct main",
            "provider": "direct main",
            "crypto": "direct main",
            "file_picker": "direct main",
            "sqlite3": "transitive",
            "markdown": "transitive",
            "flutter_markdown_plus": "direct main",
        }
        result = audit_lockfile(_lock_text(functional))
        assert result.hits == ()
        assert result.is_clean

    def test_custom_and_empty_patterns(self):
        text = _lock_text({"sentry_flutter": "transitive"})
        assert audit_lockfile(text, patterns=("sent",)).hits == ("sentry_flutter",)
        assert audit_lockfile(text, patterns=()).hits == ()

    def test_empty_lock_audit_clean(self):
        result = audit_lockfile("")
        assert result.package_count == 0
        assert result.hits == ()
        assert result.is_clean

    def test_lockfile_str_content_object(self):
        text = _lock_text(
            {"dio": "direct main", "sentry_flutter": "transitive"}
        )
        result = audit_lockfile(text)
        assert result.package_count == 2
        assert result.hits == ("sentry_flutter",)

    def test_lockfile_str_missing_packages(self):
        assert audit_lockfile("sdks:\n  dart: x\n").package_count == 0
        assert audit_lockfile("").package_count == 0
        assert audit_lockfile("packages: not-a-section\n").package_count == 0

    def test_lockfile_dict_input_rejected(self):
        with pytest.raises(TypeError):
            audit_lockfile({"packages": {"dio": {"dependency": "direct main"}}})


class TestRealProjectAudit:
    def test_real_lock_zero_hits(self):
        result = audit_lockfile(LOCK.read_text(encoding="utf-8"))
        assert result.package_count >= 100
        assert result.hits == ()
        assert result.is_clean

    def test_real_project_clean_and_resolved(self):
        result = audit_project(REPO_ROOT)
        assert result.package_count >= 100
        assert result.hits == ()
        assert result.unresolved_direct == ()
        assert result.is_clean


class TestAuditProject:
    def test_clean_project(self, tmp_path):
        _write_project(
            tmp_path,
            "name: demo\ndependencies:\n  dio: ^5.11.0\n  drift: ^2.34.3\n"
            "dev_dependencies:\n  flutter_lints: ^6.0.0\n",
            _lock_text(
                {
                    "dio": "direct main",
                    "drift": "direct main",
                    "flutter_lints": "direct dev",
                }
            ),
        )
        result = audit_project(tmp_path)
        assert result.package_count == 3
        assert result.hits == ()
        assert result.unresolved_direct == ()
        assert result.is_clean

    def test_unresolved_direct_detected(self, tmp_path):
        _write_project(
            tmp_path,
            "name: demo\ndependencies:\n  appsflyer_sdk: ^1.0.0\n",
            _lock_text({"dio": "transitive"}),
        )
        result = audit_project(tmp_path)
        assert result.unresolved_direct == ("appsflyer_sdk",)
        assert not result.is_clean

    def test_missing_input_files_raise(self, tmp_path):
        with pytest.raises(FileNotFoundError):
            audit_project(tmp_path)
        (tmp_path / "pubspec.yaml").write_text("name: demo\n", encoding="utf-8")
        with pytest.raises(FileNotFoundError):
            audit_project(tmp_path)


class TestCli:
    def test_main_clean_exit_zero(self, tmp_path, capsys, monkeypatch):
        _write_project(
            tmp_path,
            "name: demo\ndependencies:\n  dio: ^5.11.0\n",
            _lock_text({"dio": "direct main"}),
        )
        monkeypatch.chdir(tmp_path)
        assert main([]) == 0
        out = capsys.readouterr().out
        assert "OK" in out
        assert "零第三方 SDK 追踪" in out

    def test_main_hits_exit_one(self, tmp_path, capsys, monkeypatch):
        _write_project(
            tmp_path,
            "name: demo\ndependencies:\n  sentry_flutter: ^1.0.0\n",
            _lock_text({"sentry_flutter": "direct main"}),
        )
        monkeypatch.chdir(tmp_path)
        assert main([]) == 1
        out = capsys.readouterr().out
        assert "sentry_flutter" in out

    def test_main_missing_lock_exit_one(self, tmp_path, capsys, monkeypatch):
        (tmp_path / "pubspec.yaml").write_text("name: demo\n", encoding="utf-8")
        monkeypatch.chdir(tmp_path)
        assert main([]) == 1
        out = capsys.readouterr().out
        assert "缺少审计输入" in out

    def test_main_unresolved_direct_exit_one(self, tmp_path, capsys, monkeypatch):
        _write_project(
            tmp_path,
            "name: demo\ndependencies:\n  appsflyer_sdk: ^1.0.0\n",
            _lock_text({"dio": "transitive"}),
        )
        monkeypatch.chdir(tmp_path)
        assert main([]) == 1
        out = capsys.readouterr().out
        assert "未在 pubspec.lock 解析" in out


class TestCliAsScript:
    def test_run_as_script_on_real_repo_exit_zero(self):
        # 以脚本方式执行（覆盖 __main__ 守卫），对真实 worktree 跑一遍完整审计
        proc = __import__("subprocess").run(
            [sys.executable, "scripts/privacy_audit.py"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            encoding="utf-8",
        )
        assert proc.returncode == 0
        assert "零第三方 SDK 追踪" in proc.stdout


def test_module_exports_importable():
    for name in privacy_audit.__all__:
        assert hasattr(privacy_audit, name)
    assert isinstance(TRACKING_PATTERNS, tuple)
    assert "appsflyer" in TRACKING_PATTERNS
